pipeline {
    agent any

    stages
        stage('Build') {
            steps {
            git 'https://github.com/klimd01/dyplomna_robota/tree/second'
            sh './mvnw clean compile'
            }
        }
        stage('Test') {
            steps {
                sh './mvnw test'
            }

            post {
                always {
                    junit'**/test/java/tests/NTUtests.java'
                }
            }
        }
    }
}